spring.application.name=skakki
server.port=8080
spring.datasource.url=${SKAKKI_DB_URL}
spring.datasource.username=${SKAKKI_DB_USER}
spring.datasource.password=${SKAKKI_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# _method field for making "put"/"delete" requests in an html form
spring.mvc.hiddenmethod.filter.enabled=true
